apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: devicehub-storage-temp-pvc
  labels:
    app.kubernetes.io/name: devicehub-storage-temp
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
