apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rethinkdb

resources:
  - namespace.yaml
  - rethinkdb-pvc.yaml
  - rethinkdb-service.yaml
  - rethinkdb-statefulset.yaml
  - rethinkdb-network-policy.yaml
  - stf-migrate-job.yaml

images:
  - name: ghcr.io/mdub1na/stf
    digest: sha256:9da0a528f91c5ced4594ee1706392042808819276675311827e516b4971c4e81
