apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: devicehub-platform
  source:
    repoURL: https://github.com/mdub1na/stf.git
    targetRevision: develop
    path: kuber/gitops/traefik
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
