apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openldap

resources:
  - namespace.yaml
  - openldap-service.yaml
  - openldap-pvc.yaml
  - openldap-statefulset.yaml
  - phpldapadmin-service.yaml
  - phpldapadmin-deployment.yaml
  - phpldapadmin-issuer.yaml
  - phpldapadmin-ingress.yaml
