apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    providers:
      kubernetesIngress:
        publishedService:
          enabled: false
    additionalArguments:
      - "--providers.kubernetesingress.ingressendpoint.ip=192.168.0.121"
    updateStrategy:
      rollingUpdate:
        maxUnavailable: 1
        maxSurge: 0
